#!/bin/bash
# Generated by switchwall.sh - Don't modify it by yourself.
# Time: Tue 16 Sep 16:19:40 CEST 2025

pkill -f -9 mpvpaper

for monitor in $(hyprctl monitors -j | jq -r '.[] | .name'); do
    mpvpaper -o "no-audio loop hwdec=auto scale=bilinear interpolation=no video-sync=display-resample panscan=1.0 video-scale-x=1.0 video-scale-y=1.0 video-align-x=0.5 video-align-y=0.5 load-scripts=no" "$monitor" "/home/vatnar/Pictures/wallpapers/temple-gate-amidst-autumn-mountains-moewalls-com.mp4" &
    sleep 0.1
done
